### ISSUE TITLE
Redstone Ore texture didn't update to 1.17 style.

### ISSUE THREAD

**Issue by ShulkerSakura** [Poudingue/Vanilla-Normals-Renewed#37]
Just like title ,and I found that some item's texture like bucket(Water,Lava,etc..) in some PBR support shaders hava texture issue,(like a outline or something else) hope fix it up early :)

**Comment by ShulkerSakura** [comment]
Some shaders like Complementary Shaders

**Comment by Poudingue** [comment]
Yes, I know, that’s the next thing I’ll update ! Other ores are still in the 1.16 style, I first need to do the deepslate, then I’ll redo all the ores.

![image](https://user-images.githubusercontent.com/18035775/130828009-6d5aa7b6-ce88-41a6-8f4a-93e8a643f30a.png)

For the "outline", that’s probably due to the way the shaders handle extreme normals. I could try to lessen the normals intensity, but it wouldn’t look the way I like it 😦
I’ll look into it if I have time.
