### ISSUE TITLE
Green reflections on PTGI

### ISSUE THREAD

**Issue by HenriqueGomez** [Poudingue/Vanilla-Normals-Renewed#38]
Hello,
I noticed that all reflections have a green tint to its color, as shown in the image.
![Base Profile Screenshot 2021 08 25 - 01 14 50 54](https://user-images.githubusercontent.com/11247187/130725775-e1460a62-cb30-4ba7-b41e-c76872177e98.png)

**Comment by Poudingue** [comment]
Hello,
That’s due to the slightly metallic appearance I gave to all the diamond textures.
There’s a slight tinting, I modified it to appear more blue than green, but in a case like this with yellow lighting, the green comes out.
Also, that’s partly due to the fact that PTGI does not handle f0 information, shaders that do have zero tinting on the reflection, the reflection is just more intense, and that’s what I’m going for, for most shaders.
